### ISSUE TITLE
Bug installing dependencies

### ISSUE THREAD

**Issue by zwzone** [smakosh/1337-next.js-2024#1]
Salam Alaikum Smail.

I wanted to say thanks for the awesome Next.js talk! It was super informative and really helped me understand the framework better.

I cloned your GitHub repository and tried running `npm i`, but it didn’t work. I ran into some issues, so I just wanted to let you know in case there’s something I missed or if I need to install any dependencies first.

Appreciate your help, and thanks again for the great session!

![Screenshot from 2024-12-13 18-07-02](https://github.com/user-attachments/assets/f410dbc8-eea4-456b-954f-6f9ff0f01227)

**Comment by smakosh** [comment]
the repository contains pnpm lock file, so you should use `pnpm` rather than `npm`, here's a link to install pnpm: https://pnpm.io, also make sure you're using at least Node 20.

My bad, I should have written some documentation on how to start this locally, let me do that right now.

**Comment by smakosh** [comment]
README has been updated

**Comment by zwzone** [comment]
It works right now. Thank you so much.
